export const START_FETCH_WEATHER_DETAIL = 'START_FETCH_WEATHER_DETAIL';
export const SUCCESS_FETCH_WEATHER_DETAIL = 'SUCCESS_FETCH_WEATHER_DETAIL';
export const ERROR_FETCH_WEATHER_DETAIL = 'ERROR_FETCH_WEATHER_DETAIL';
export const RESET_WEATHER_LIST = 'RESET_WEATHER_LIST';

export const SET_SELECTED_WEATHER_DETAIL = 'SET_SELECTED_WEATHER_DETAIL';
export const RESET_SELECTED_WEATHER_DETAIL = 'RESET_SELECTED_WEATHER_DETAIL';

export const SET_GLOBAL_LOADER_STATUS = 'SET_GLOBAL_LOADER_STATUS';

export const UPDATE_WEATHER_LIST_DATA = 'UPDATE_WEATHER_LIST_DATA';
